# Generated by Django 6.0.3 on 2026-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystory',
            name='level_at_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
