# Generated by Django 6.0.3 on 2026-03-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_dailystory_level_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystory',
            name='exp_gained',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='found_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='steps_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='world_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
