# Generated by Django 6.0.3 on 2026-03-21 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_dailystory_exp_gained_dailystory_found_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystory',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
