# Generated by Django 6.0.3 on 2026-03-05 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=10)),
                ('character_class', models.CharField(default='Novice', max_length=50)),
                ('character_location', models.CharField(default='The Humble Village of Starting', max_length=255)),
                ('world_region', models.CharField(default='Greenleaf Kingdom', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
