# Generated by Django 6.0.3 on 2026-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='ai_seed',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='visual_player_description',
            field=models.TextField(default='Male Isekai protagonist, messy black hair, sharp blue eyes, athletic build'),
        ),
    ]
