# Generated by Django 6.0.3 on 2026-03-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerprofile_ai_seed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='visual_player_description',
            new_name='visual_description',
        ),
    ]
