# Generated by Django 6.0.3 on 2026-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_visual_player_description_playerprofile_visual_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='character_location',
            new_name='current_location',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='character_class',
            field=models.CharField(default='Novice', max_length=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='hp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='mana',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
