# Generated by Django 6.0.3 on 2026-03-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_rename_character_location_playerprofile_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='google_client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='google_client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='google_token_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
