# Generated by Django 6.0.3 on 2026-03-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_playerprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('CONSUMABLE', 'Consumable'), ('ARTIFACT', 'Artifact')], max_length=20)),
                ('rarity', models.CharField(default='Common', max_length=20)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('mana_bonus', models.IntegerField(default=0)),
                ('exp_multiplier', models.FloatField(default=1.0)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='players.playerprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.item')),
            ],
        ),
    ]
