# Generated by Django 6.0.3 on 2026-04-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_inventoryitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='hp',
            new_name='base_hp',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='mana',
            new_name='base_mana',
        ),
    ]
