# Generated by Django 6.0.3 on 2026-05-24 12:09

import players.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_rename_hp_playerprofile_base_hp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='google_client_id',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='google_client_secret',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='google_token_uri',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='google_access_token',
            field=players.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='google_refresh_token',
            field=players.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
