# Generated by Django 6.0.3 on 2026-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysteplog',
            name='level_at_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailysteplog',
            name='story_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dailysteplog',
            name='story_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysteplog',
            name='date',
            field=models.DateField(),
        ),
    ]
