# Generated by Django 6.0.3 on 2026-03-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_inventoryitem_quantity'),
        ('tracker', '0002_dailysteplog_level_at_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField()),
                ('exp_gained', models.PositiveIntegerField()),
                ('leveled_up', models.BooleanField(default=False)),
                ('target_level', models.PositiveIntegerField(blank=True, null=True)),
                ('story_date', models.CharField(blank=True, max_length=50, null=True)),
                ('found_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerprofile')),
            ],
        ),
    ]
